config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  # nested 
  resources :users, only: [:show] do
    get 'favorites', to: 'users#favorites'
    get 'teas', to: 'users#teas'
    resources :badges, only: [:index] #view index only for user
    resources :teas, only: [:new, :edit] #new/create & edit/update options for user submitted data
    resources :benefits, only: [:new, :create, :edit, :update]
    resources :ingredients, only: [:new, :create, :edit, :update]
  end

  resources :favorites, only: [:create, :destroy]
  resources :tasted, only: [:create, :destroy]

  # tea scope method url
  get '/teas/latest', to: 'teas#latest'
 
  resources :teas, only: [:index, :show, :create, :update, :destroy] #view all teas, or single tea profile
  resources :benefits, only: [:index, :show]
  resources :ingredients, only: [:index, :show]

end

app/models/tea.rb
class Tea < ApplicationRecord
    has_many :user_teas
    has_many :users, through: :user_teas
    has_many :tea_ingredients
    has_many :ingredients, through: :tea_ingredients
    has_many :tea_benefits
    has_many :benefits, through: :tea_benefits

    validates :name, presence: true, uniqueness: { case_sensitive: false }
    validates_presence_of :preparation

    accepts_nested_attributes_for :benefits, :ingredients

    scope :with_ingredient, ->(ingredient_name) { includes(:ingredients).where(ingredients: { name: ingredient_name }) }
    scope :with_benefit, ->(benefit_name) { includes(:benefits).where(benefits: { name: benefit_name }) }
    scope :created_by, ->(user_id) { where(user_id: user_id) }

    def benefits_attributes=(benefit_attributes)
      benefit_attributes.values.each do |benefit_attribute|
        if benefit_attribute["name"].present?
          benefit = Benefit.find_or_create_by(benefit_attribute)
          self.benefits << benefit
        end
      end
    end

    def ingredients_attributes=(ingredient_attributes)
      ingredient_attributes.values.each do |ingredient_attribute|
        if ingredient_attribute["name"].present?
          ingredient = Ingredient.find_or_create_by(ingredient_attribute)
          self.ingredients << ingredient
        end
      end
    end
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController

    #GET - Tea.newest scope method
    def latest
        @latest_teas = Tea.all.order(:name).last(3)
    end

    #GET - Index => /teas
    def index
        @teas = Tea.all
    end

    #GET - New (render form) => /teas/new
    def new
        @tea = Tea.new
        @benefits = @tea.benefits.build
        @ingredients = @tea.ingredients.build
    end

    #POST - Create => /teas
    def create
        @tea = Tea.create(tea_params)
        respond_to do |format|
          if @tea.save
            current_user.teas << @tea
            format.html { redirect_to @tea, notice: "Tea was successfully created."}
            format.json { render :show, status: :created, location: @tea }
          else
            format.html { render :new }
            format.json { render json: @tea.errors.full_messages, status: :unproccessable_entity }
          end
        end
    end

    #GET - Edit (render form) => /teas/:id/edit
    def edit
        @tea = Tea.find(params[:id])
        @benefits = @tea.benefits.build
        @ingredients = @tea.ingredients.build
    end

    #PATCH - Update => /teas/:id
    def update
        @tea = Tea.find(params[:id])
        @tea.update(tea_params)
        respond_to do |format|
            if @tea.save
              format.html { redirect_to @tea, notice: 'Tea was successfully updated.' }
              format.json { render action: 'show', status: :created, location: @tea }
            else
              format.html { render action: 'edit' }
              format.json { render json: @tea.errors, status: :unprocessable_entity }
            end
        end
    end

    #GET - Read/Show => /teas/:id
    def show
        if user_signed_in?
            @tea = Tea.find(params[:id])
        else
            redirect_to teas_path, notice: "You must be signed in to view any tea profiles!"
        end
    end

    #DELETE - Destroy => /teas/:id
    def destroy
        @tea = Tea.find(params[:id])
        @tea.users.clear
        @tea.ingredients.clear
        @tea.benefits.clear
        @tea.destroy
        redirect_to user_teas_path(current_user.id), notice: "Tea successfully deleted!"
    end
    
    private

    def tea_params
        params.require(:tea).permit(:name, :preparation, :user_id, :benefit_ids => [], :benefits_attributes => [:name], :ingredient_ids => [], :ingredients_attributes => [:name])
    end

end

app/views/teas/_form.html.erb
<%# Errors %>
<% if @tea.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <strong><%= pluralize(@tea.errors.count, "error") %> prohibited this tea from being saved:</strong>
        <ul>
            <% @tea.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_with model: @tea do |f| %>
    <div class="mb-3">
    <%# Tea Name and Preparation %>
    <%= f.text_field :name, class:"form-control", placeholder: "Tea Name" %>
    <br>
    <%= f.text_area :preparation, class:"form-control", placeholder: "Instructions for preparation..." %>
    <br>

    <%# Association to User %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%# Select or Create Benefits %>
    <fieldset>
    <legend>Benefits</legend>
        <%= f.label "Select Pre-Existing Benefits:" %><br>
        <%= f.collection_check_boxes :benefit_ids, Benefit.all, :id, :name %>
        <br>
        <br>
        <%= f.fields_for :benefits, @tea.benefits.build do |benefit| %>
            <%= benefit.text_field :name, class:"form-control", placeholder: "Create New Benefit"  %>
        <% end %>
    </fieldset>
    <br>
    <%# Select or Create Ingredients %>
    <fieldset>
    <legend>Ingredients</legend>
        <%= f.label "Select Pre-Existing Ingredients:" %><br>
        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
        <br>
        <br>
        <%= f.fields_for :ingredients, @tea.ingredients.build do |ingredient| %>
        <%= ingredient.text_field :name, class:"form-control", placeholder: "Create New Ingredient" %>
        <% end %>
    </fieldset>
    <br>
    
    <%= f.submit %>
    </div>
<% end %>

app/views/teas/edit.html.erb
<h1>Edit Tea</h1>

<%= render 'form' %>

app/views/teas/index.html.erb
<h1> Teas </h1>

<ul class="list-group list-group-flush">
    <% @teas.each do |tea| %>
        <li class="list-group-item"><%= link_to "#{tea.name}", tea_path(tea.id) %></li>
    <% end %>
</ul>

app/views/teas/latest.html.erb
<h1>Our Newest Additions</h1>

<ul>
    <% @latest_teas.each do |tea| %>
        <li><%= link_to "#{tea.name}", tea_path(tea.id) %> | <%= tea.created_at %> </li>
    <% end %>
</ul>

app/views/teas/new.html.erb
<h1>Create Tea</h1>

<%= render 'form' %>

app/views/teas/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="text-end"><%= @tea.name %></h1>
        </div>
        <div class="col">
            <br>
            <br>
            <div class="border-start">
                <div class="ps-3">
                    <h4>Preparation</h4>
                    <%= @tea.preparation%>
                    <br>
                    <br>
                    <strong>Benefits</strong>
                    <% @tea.benefits.each do |benefit| %>
                        | <%= link_to "#{benefit.name}", benefit_path(benefit.id) %>
                    <% end %>
                    <br>
                    <br>
                    <strong>Ingredients</strong>
                    <% @tea.ingredients.each do |ingredient| %>
                        | <%= link_to "#{ingredient.name}", ingredient_path(ingredient.id) %>
                    <% end %>
                    <br>
                    <br>
                    <table>
                        <tr>
                            <th><%= toggle_favorite(@tea) %></th>
                            <th><%= toggle_tasted(@tea) %></th>
                            <% if current_user.id == @tea.user_id %>
                                <th><%= link_to "Edit", edit_user_tea_path(@tea.id), class:"btn btn-outline-secondary"%></th>
                                <th><%= button_to "Delete", tea_path(@tea.id), method: :delete, class:"btn btn-outline-dark" %></th>
                            <% end %>
                            <th><%= link_to "Back", teas_path, class:"btn btn-dark" %></th>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>