config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  # nested 
  resources :users, only: [:show] do
    get 'favorites', to: 'users#favorites'
    get 'teas', to: 'users#teas'
    resources :badges, only: [:index] #view index only for user
    resources :teas, only: [:new, :edit] #new/create & edit/update options for user submitted data
    resources :benefits, only: [:new, :create, :edit, :update]
    resources :ingredients, only: [:new, :create, :edit, :update]
  end

  resources :favorites, only: [:create, :destroy]
  resources :tasted, only: [:create, :destroy]

  # tea scope method url
  get '/teas/latest', to: 'teas#latest'
 
  resources :teas, only: [:index, :show, :create, :update, :destroy] #view all teas, or single tea profile
  resources :benefits, only: [:index, :show]
  resources :ingredients, only: [:index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :badges, dependent: :destroy
  has_many :user_teas
  has_many :teas, through: :user_teas

  after_create :add_badges

  # Public methods

  def favorite!(tea)
    tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
    if tea_saved
        tea_saved.favorite = true
        tea_saved.save!
    else
        self.teas << tea
        self.save!
        tea.save!
        new_tea = UserTea.find_by(user_id: self.id, tea_id: tea.id)
        new_tea.favorite = true
        new_tea.save!
    end
  end

  def unfavorite!(tea)
      tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
      if tea_saved
          tea_saved.favorite = false
          tea_saved.save!
      end
  end

  def total_favorites
    count = 0
    self.teas.each do |tea|
      tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
      if tea_saved.favorite == true
        count += 1
      end
    end
    count
  end

  def all_favorites
    favorites = []
    self.teas.each do |tea|
      tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
      if tea_saved.favorite == true
        favorites << tea
      end
    end
    favorites
  end

  def taste!(tea)
    tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
    if tea_saved
        tea_saved.tasted = true
        tea_saved.save!
    else
        self.teas << tea
        self.save!
        tea.save!
        new_tea = UserTea.find_by(user_id: self.id, tea_id: tea.id)
        new_tea.tasted = true
        new_tea.save!
    end
  end

  def untaste!(tea)
      tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
      if tea_saved
          tea_saved.tasted = false
          tea_saved.save!
      end
  end

  def total_tasted
    count = 0
    self.teas.each do |tea|
      tea_saved = UserTea.find_by(user_id: self.id, tea_id: tea.id)
      if tea_saved.tasted == true
        count += 1
      end
    end
    count
  end

  private

    def add_badges
      badges = [
        {user_id: "#{self.id}", title: "Tiny Taster", body: "You've tasted at least 1 tea!"}, 
        {user_id: "#{self.id}", title: "Taste Tester", body: "You've tasted at least 5 teas!"}, 
        {user_id: "#{self.id}", title: "I Came, I Saw, I Tasted", body: "You've tasted at least 10 teas!"}, 
        {user_id: "#{self.id}", title: "Flavor Fav", body: "You've added at least 1 tea to your favorites!"}, 
        {user_id: "#{self.id}", title: "Super Flavor Fav", body: "You've added at least 5 teas to your favorites!"}
        ]
      badges.each do |b|
        badge = Badge.create(b)
        self.badges << badge
      end
      self.save
    end

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.name = auth.info.name
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/github/callback
  def failure
    redirect_to root_path
  end
  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    #GET - Read/Show => /users/:id
    def show
        @user = current_user
        @total_favs = @user.total_favorites
        @total_created = Tea.created_by(@user.id).count
        @total_tasted = @user.total_tasted
        @total_badges = Badge.earned(@user.id).count
        @favorites = @user.all_favorites
        @badges = Badge.earned(@user.id)
    end
    
    #GET - Read/Show => /users/:id/teas
    def teas
        @user = current_user
        @teas = Tea.created_by(@user.id)
    end

    #GET - Read/Show => /users/:id/favorites
    def favorites
        @user = current_user
        @favorites = @user.all_favorites
    end

end

app/views/users/favorites.html.erb
<h1>Your Favorites</h1>

<ul class="list-group list-group-flush">
    <% @favorites.each do |fav| %>
        <li class="list-group-item">
            <%= link_to "#{fav.name}", tea_path(fav.id) %>
        </li>
    <% end %>
</ul>

app/views/users/show.html.erb
<div class="container">
    <h1>Your Profile</h1>
    <div class="card p-3">
        <div class="row g-0">
            <div class="col-6 col-md-4">
                <img src="<%= image_url("lemon.png") %>" class="img-fluid" alt="...">
            </div>
            <div class="col-sm-6 col-md-8">
                <div class="ml-3 w-100">
                    <h2><%= current_user.name %></h2>
                    <button type="button" class="btn btn-outline-dark">Teas Tasted: <%= @total_tasted%></button>
                    <button type="button" class="btn btn-outline-danger">Teas Loved: <%= @total_favs%></button>
                    <button type="button" class="btn btn-outline-info">Badges Earned: <%= @total_badges%></button>
                    <button type="button" class="btn btn-outline-success">Teas Created: <%= @total_created %></button>
                    <br/>
                    <br/>
                    <div class="row">
                        <div class="col">
                            <div class="card text-center">
                                <div class="card-body">
                                    <h4 class="card-title">Badges</h4>
                                <ul class="list-group list-group-flush">
                                    <% @badges.last(3).each do |bad| %>
                                    <li class="list-group-item"><%= bad.name %></li>
                                    <% end %>
                                </ul>
                                </div>
                                <div class="card-body">
                                    <%= link_to "View All", user_badges_path(current_user.id), class:"btn btn-light" %>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card text-center">
                                <div class="card-body">
                                    <h4 class="card-title">Favorites</h4>
                                <ul class="list-group list-group-flush">
                                    <% @favorites.last(3).each do |fav| %>
                                    <li class="list-group-item"><%= fav.name %></li>
                                    <% end %>
                                </ul>
                                </div>
                                <div class="card-body">
                                    <%= link_to "View All", user_favorites_path(current_user.id), class:"btn btn-light" %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br/>
                </div>
            </div>
            <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-dark btn-lg" %>
        </div>
    </div>
</div>

app/views/users/teas.html.erb
<h1>Your Teas</h1>

<ul class="list-group list-group-flush">
    <% @teas.each do |tea| %>
        <li class="list-group-item">
            <%= link_to "#{tea.name}", tea_path(tea.id) %>
        </li>
    <% end %>
</ul>