config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  # nested 
  resources :users, only: [:show] do
    get 'favorites', to: 'users#favorites'
    get 'teas', to: 'users#teas'
    resources :badges, only: [:index] #view index only for user
    resources :teas, only: [:new, :edit] #new/create & edit/update options for user submitted data
    resources :benefits, only: [:new, :create, :edit, :update]
    resources :ingredients, only: [:new, :create, :edit, :update]
  end

  resources :favorites, only: [:create, :destroy]
  resources :tasted, only: [:create, :destroy]

  # tea scope method url
  get '/teas/latest', to: 'teas#latest'
 
  resources :teas, only: [:index, :show, :create, :update, :destroy] #view all teas, or single tea profile
  resources :benefits, only: [:index, :show]
  resources :ingredients, only: [:index, :show]

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :tea_ingredients
    has_many :teas, through: :tea_ingredients

    validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    #GET - Index => /ingredients
    def index
        @ingredients = Ingredient.all
    end

    #GET - New (render form) => /ingredients/new
    def new
        @ingredient = Ingredient.new
    end

    #POST - Create => /ingredients
    def create
        @ingredient = Ingredient.new
        @ingredient.name = params[:name]
        @ingredient.save
        redirect_to ingredient_path(@ingredient)
    end

    #GET - Edit (render form) => /ingredients/:id/edit
    def edit
    end

    #PATCH - Update => /ingredients/:id
    def update
    end

    #GET - Read/Show => /ingredients/:id
    def show
        @ingredient = Ingredient.find(params[:id])
        @tea_list = Tea.with_ingredient(@ingredient.name)
    end

    #DELETE - Destroy => /ingredients/:id
    def destroy
    end
    
end

app/views/ingredients/index.html.erb
<h1> Ingredients </h1>

<ul class="list-group list-group-flush">
    <% @ingredients.each do |ing| %>
        <li class="list-group-item"><%= link_to "#{ing.name}", ingredient_path(ing.id) %></li>
    <% end %>
</ul>

app/views/ingredients/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="text-end"><%= @ingredient.name %></h1>
        </div>
        <div class="col">
            <br/>
            <br/>
            <div class="border-start">
                <div class="ps-3">
                    <ul class="list-group list-group-flush">
                        <% @tea_list.each do |tea| %>
                            <li class="list-group-item"><%= link_to "#{tea.name}", tea_path(tea.id) %></li>
                        <% end %>
                    </ul>
                    <br/>
                    <%= link_to "Back", ingredients_path, class:"btn btn-dark" %>
                </div>
            </div>
        </div>
    </div>
</div>