config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  # nested 
  resources :users, only: [:show] do
    get 'favorites', to: 'users#favorites'
    get 'teas', to: 'users#teas'
    resources :badges, only: [:index] #view index only for user
    resources :teas, only: [:new, :edit] #new/create & edit/update options for user submitted data
    resources :benefits, only: [:new, :create, :edit, :update]
    resources :ingredients, only: [:new, :create, :edit, :update]
  end

  resources :favorites, only: [:create, :destroy]
  resources :tasted, only: [:create, :destroy]

  # tea scope method url
  get '/teas/latest', to: 'teas#latest'
 
  resources :teas, only: [:index, :show, :create, :update, :destroy] #view all teas, or single tea profile
  resources :benefits, only: [:index, :show]
  resources :ingredients, only: [:index, :show]

end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <%= link_to 'VarieTea', root_path, class:"navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <%# login/logout/signup buttons build into navigation bar... sign up on home page as well. %>
                <% if user_signed_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Hi, <%= current_user.name %>!</a>
                        <ul class="dropdown-menu">
                        <li><%= link_to "Profile", user_path(current_user.id), class:"dropdown-item" %></li>
                        <li><%= link_to "Latest Teas", teas_latest_path, class:"dropdown-item" %></li>
                        <li><%= link_to "My Teas", user_teas_path(current_user.id), class:"dropdown-item" %></li>
                        <li><%= link_to "Favorites", user_favorites_path(current_user.id), class:"dropdown-item" %></li>
                        <li><%= link_to "New Tea", new_user_tea_path(current_user.id), class:"dropdown-item" %></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><%= button_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
                        </ul>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Login",
                        new_user_session_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "SignUp",
                        new_user_registration_path, class:"nav-link" %>
                    </li>
                <% end %>

                <li class="nav-item">
                    <%= link_to "Teas",
                    teas_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Benefits",
                    benefits_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Ingredients",
                    ingredients_path, class:"nav-link" %>
                </li>
            </ul>

            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>VarieTea</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c1c9d6bc5d.js" crossorigin="anonymous"></script>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <br/>

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

    <!-- Optional JavaScript; Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>